### ISSUE TITLE
Docker: /root/dlang/ldc-1.27.0/bin/ldc2 failed with exit code 1

### ISSUE THREAD

**Issue by Kekananen** [blachlylab/recontig#16]
For the docker image to load, this will need to be addressed. This may be related to the newest fixed in dhtslib, since the `hts_log` references were extensively referred to in the latest fixes. Also went up to 1.13 instead of what was used in dev as 1.12.
```
(ldc-1.27.0)# dub build
Fetching dhtslib ~develop (getting selected version)...
Fetching pyd 0.14.1 (getting selected version)...
WARNING: A deprecated branch based version specification is used for the dependency dhtslib. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Performing "debug" build using /root/dlang/ldc-1.27.0/bin/ldc2 for x86_64.
dhtslib ~develop: building configuration "unittest"...
recontig 1.1.1: building configuration "standard"...
source/recontig/bam.d(141,26): Deprecation: constructor `dhtslib.sam.record.SAMRecord.this` is deprecated - Construct with sam_hdr_t* for mapped contig (tid) name support
Linking...
/usr/bin/ld.gold: error: cannot find -lhts
source/recontig/vcf.d:24: error: undefined reference to 'bcf_hdr_dup'
source/recontig/vcf.d:26: error: undefined reference to 'bcf_hdr_remove'
//root/.dub/packages/dhtslib-develop/dhtslib/source/htslib/hts_log.d:92: error: undefined reference to 'hts_log'
source/recontig/vcf.d:37: error: undefined reference to 'bcf_hdr_get_hrec'
source/recontig/vcf.d:37: error: undefined reference to 'bcf_hrec_dup'
source/recontig/vcf.d:40: error: undefined reference to 'bcf_hrec_find_key'
source/recontig/vcf.d:42: error: undefined reference to 'bcf_hrec_set_val'
source/recontig/vcf.d:46: error: undefined reference to 'bcf_hdr_add_hrec'
//root/.dub/packages/dhtslib-develop/dhtslib/source/htslib/hts_log.d:81: error: undefined reference to 'hts_log'
source/recontig/vcf.d:57: error: undefined reference to 'bcf_hdr_sync'
//root/.dub/packages/dhtslib-develop/dhtslib/source/htslib/hts_log.d:116: error: undefined reference to 'hts_log'
//root/.dub/packages/dhtslib-develop/dhtslib/source/htslib/hts_log.d:92: error: undefined reference to 'hts_log'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/writer.d:59: error: undefined reference to 'hts_open'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/writer.d:62: error: undefined reference to 'bcf_hdr_dup'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/faidx.d:157: error: undefined reference to 'faidx_fetch_seq64'
source/recontig/mapping.d:0: error: undefined reference to 'seq_nt16_table'
source/recontig/mapping.d:0: error: undefined reference to 'seq_nt16_int'
source/recontig/bam.d:39: error: undefined reference to 'sam_hdr_remove_line_id'
source/recontig/bam.d:39: error: undefined reference to 'sam_hdr_remove_line_id'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:77: error: undefined reference to 'hts_open'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:96: error: undefined reference to 'hts_set_threads'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:103: error: undefined reference to 'hts_set_threads'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:115: error: undefined reference to 'sam_hdr_read'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:116: error: undefined reference to 'sam_index_load'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/header.d:189: error: undefined reference to 'sam_hdr_add_line'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/writer.d:88: error: undefined reference to 'hts_open'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/writer.d:108: error: undefined reference to 'hts_set_threads'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/writer.d:115: error: undefined reference to 'hts_set_threads'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/writer.d:128: error: undefined reference to 'sam_hdr_write'
//root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/header.d:189: error: undefined reference to 'sam_hdr_add_line'
source/app.d:139: error: undefined reference to 'hts_set_log_level'
source/app.d:140: error: undefined reference to 'hts_set_log_level'
source/app.d:141: error: undefined reference to 'hts_set_log_level'
source/app.d:142: error: undefined reference to 'hts_set_log_level'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/bgzf.d:56: error: undefined reference to 'bgzf_open'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/bgzf.d:63: error: undefined reference to 'bgzf_mt'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/bgzf.d:81: error: undefined reference to 'bgzf_close'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/bgzf.d:152: error: undefined reference to 'hseek'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/bgzf.d:142: error: undefined reference to 'bgzf_getline'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/faidx.d:69: error: undefined reference to 'fai_load3'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/faidx.d:73: error: undefined reference to 'fai_load3'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/faidx.d:81: error: undefined reference to 'fai_destroy'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/faidx.d:179: error: undefined reference to 'faidx_nseq'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/faidx.d:189: error: undefined reference to 'faidx_iseq'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/faidx.d:198: error: undefined reference to 'faidx_seq_len'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/header.d:58: error: undefined reference to 'sam_hdr_destroy'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/header.d:67: error: undefined reference to 'sam_hdr_dup'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/header.d:106: error: undefined reference to 'sam_hdr_name2tid'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:143: error: undefined reference to 'hts_close'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:423: error: undefined reference to 'sam_itr_queryi'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:513: error: undefined reference to 'bam_init1'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:516: error: undefined reference to 'hseek'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:446: error: undefined reference to 'bam_init1'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:449: error: undefined reference to 'bgzf_seek'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:581: error: undefined reference to 'bam_init1'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:478: error: undefined reference to 'sam_read1'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:485: error: undefined reference to 'bam_dup1'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:490: error: undefined reference to 'bam_dup1'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:545: error: undefined reference to 'sam_read1'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:552: error: undefined reference to 'bam_dup1'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/reader.d:557: error: undefined reference to 'bam_dup1'
root/.dub/packages/dhtslib-develop/dhtslib/source/htslib/sam.d:1463: error: undefined reference to 'hts_itr_multi_next'
root/.dub/packages/dhtslib-develop/dhtslib/source/htslib/sam.d:1465: error: undefined reference to 'hts_itr_next'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/record.d:76: error: undefined reference to 'bam_destroy1'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/sam/writer.d:149: error: undefined reference to 'sam_write1'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/header.d:30: error: undefined reference to 'bcf_hdr_destroy'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/header.d:46: error: undefined reference to 'bcf_hdr_seqnames'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/reader.d:79: error: undefined reference to 'hts_open'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/reader.d:84: error: undefined reference to 'bcf_hdr_read'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/reader.d:86: error: undefined reference to 'bcf_init'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/reader.d:101: error: undefined reference to 'hts_close'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/reader.d:109: error: undefined reference to 'bcf_destroy'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/reader.d:174: error: undefined reference to 'bcf_read'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/reader.d:204: error: undefined reference to 'bcf_dup'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/record.d:149: error: undefined reference to 'bcf_destroy'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/record.d:160: error: undefined reference to 'bcf_unpack'
root/.dub/packages/dhtslib-develop/dhtslib/source/htslib/vcf.d:1178: error: undefined reference to 'bcf_hdr_id2int'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/record.d:95: error: undefined reference to 'bcf_unpack'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/writer.d:68: error: undefined reference to 'hts_close'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/writer.d:124: error: undefined reference to 'bcf_hdr_append'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/writer.d:125: error: undefined reference to 'bcf_hdr_sync'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/writer.d:329: error: undefined reference to 'bcf_hdr_write'
root/.dub/packages/dhtslib-develop/dhtslib/source/dhtslib/vcf/writer.d:334: error: undefined reference to 'bcf_write'
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
/root/dlang/ldc-1.27.0/bin/ldc2 failed with exit code 1.
```

**Comment by charlesgregory** [comment]
So `/usr/bin/ld.gold: error: cannot find -lhts` basically just means the linker can't find the htslib shared library. So this is a linker issue. 

Looking at your docker branch, I don't think this is the correct way to set environment variables in docker. In docker each line is run in a shell so these variables disappear right after this line:
`RUN LD_LIBRARY_PATH=usr/local/htslib-1.13 LIBRARY_PATH=usr/local/htslib-1.13`

You will need to use `export` or maybe the `ENV` keyword.


Though to avoid all this, you could just base the image off miniconda and install via conda.

**Comment by Kekananen** [comment]
If the conda is broken though then both would be broken so maybe we want them to be independent? That would be the quickest way though I agree. 

`RUN LD_LIBRARY_PATH=usr/local/htslib-1.13 LIBRARY_PATH=usr/local/htslib-1.13 dub build` was run internally before to see and test. Even with setting the `RUN LD_LIBRARY_PATH=usr/local/htslib-1.13 LIBRARY_PATH=usr/local/htslib-1.13` or with `ARG LD_LIBRARY_PATH=usr/local/htslib-1.13 LIBRARY_PATH=usr/local/htslib-1.13` or by setting it internally and then straight running build dub. Haven't tried dmd yet.

For tonight I'm going to leave this.

**Comment by jblachly** [comment]
> Though to avoid all this, you could just base the image off miniconda and install via conda.

agree with Kat, would not make it dependent on Conda version functioning

> You will need to use export or maybe the ENV keyword.

`ENV` is correct and export is incorrect (export will work to fix the linking problem (`LD_LIBRARY_PATH`) but does not persist in the final container; the resulting binary when run in the container won't see the value of the export; thus the `LIBRARY_PATH` requires `ENV`)

> RUN LD_LIBRARY_PATH=usr/local/htslib-1.13 LIBRARY_PATH=usr/local/htslib-1.13 dub build was run internally before to see and test. Even with setting the RUN LD_LIBRARY_PATH=usr/local/htslib-1.13 LIBRARY_PATH=usr/local/htslib-1.13 or with ARG LD_LIBRARY_PATH=usr/local/htslib-1.13 LIBRARY_PATH=usr/local/htslib-1.13 or by setting it internally and then straight running build dub. Haven't tried dmd yet.

`ARG` is definitely wrong.
Use `ENV` as above, and absolute paths. This will solve all your problems. generally try to avoid relative paths unless you have a specific reason to use them

**Comment by Kekananen** [comment]
Yes, the absolute paths clear up this error. Had to end up building with the path directly in the build command since it wasn't picking it up as an `ENV` either for me. Since that was the case, I may have to play around in getting it to actually find the `libhts.so.3` library when executing since it's now throwing the below.
```
/usr/local/recontig/recontig: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory
```
We've run into this before, so I can play around with it.

**Comment by jblachly** [comment]
It is not working because you did not follow my instructions.

In [this commit](https://github.com/blachlylab/recontig/commit/525664d1f0ac36fa505170c937a69bdca9a5d221) you removed the ENV lines. Please go back and re-read my comment

**Comment by Kekananen** [comment]
Unless I'm doing something off or completely misreading your instructions it's not actually building an executable, though it completes and builds fine, with just setting the `ENV`. 

Compiling
```
docker build . -t recontig
[+] Building 0.3s (13/13) FINISHED                                                                    
 => [internal] load build definition from Dockerfile                                             0.0s
 => => transferring dockerfile: 37B                                                              0.0s
 => [internal] load .dockerignore                                                                0.0s
 => => transferring context: 2B                                                                  0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                  0.2s
 => [1/9] FROM docker.io/library/ubuntu:20.04@sha256:82becede498899ec668628e7cb0ad87b6e1c371cb8  0.0s
 => CACHED [2/9] RUN apt-get update                                                              0.0s
 => CACHED [3/9] RUN apt-get install -y autoconf automake make gcc     perl zlib1g-dev libbz2-d  0.0s
 => CACHED [4/9] RUN wget https://github.com/samtools/htslib/releases/download/1.13/htslib-1.13  0.0s
 => CACHED [5/9] RUN cd /usr/local/ && tar -xvf /usr/local/htslib-1.13.tar.bz2 &&     cd htslib  0.0s
 => CACHED [6/9] RUN pip install cython pyd                                                      0.0s
 => CACHED [7/9] RUN curl https://dlang.org/install.sh | bash -s ldc                             0.0s
 => CACHED [8/9] RUN cd /usr/local/ && git clone --recurse-submodules https://github.com/blachl  0.0s
 => CACHED [9/9] RUN . ~/dlang/ldc-1.27.0/activate && cd /usr/local/recontig     && python3 set  0.0s
 => exporting to image                                                                           0.0s
 => => exporting layers                                                                          0.0s
 => => writing image sha256:7db1b57083cf2ed13cee6694f77bab135c7af9bd88b3cd2e14f32dc3c5810f16     0.0s
 => => naming to docker.io/library/recontigv13 
```

But when one looks inside nothing is made.
```
b940d01ecd69 /bin/sh
# cd usr/local/recontig
# ls
INSTALL.md  README.md  dhtslib	 pyrecontig.py	source
LICENSE     build      dub.json  setup.py
```
The way I wiggled around it was by the updated docker which compiles a binary but is not linking fully either,`libhts.so.3`.

**Comment by jblachly** [comment]
It wasn't building an executable because it didn't have a `dub build` line.

**Comment by charlesgregory** [comment]
```
/usr/local/recontig/recontig: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory
```
So this means the executable cannot find the `libhts.so.3`. This almost always means `libhts.so.3` is not on the `LD_LIBRARY_PATH`. `LIBRARY_PATH` is just specific to the ldc compiler and its use of `ld.gold` for linking but is similar.

Since htslib installs into `/usr/local/lib` by default with `make install`.
Adding these lines to the docker file fixes both issues:
```
ENV LD_LIBRARY_PATH /usr/local/lib
ENV LIBRARY_PATH /usr/local/lib
```

I have pushed a commit that makes these changes and some additional ones:
1.  Good coding practice is to make environment variables (or constants) completely capitalized
2. Recontig's version is set as we don't want the docker building from master
3. moved the recontig binary from its folder to `/usr/local/bin` as this is on the linux `PATH` so you can run it without specifying the full path 
4. You should use `WORKDIR` to change directories in a docker file as otherwise many steps are one line. Other than being hard to read this doesn't allow docker to create a intermediate step for each actual step.

**Comment by Kekananen** [comment]
This is working now with the `/usr/local/lib` adjustments to the htslib paths. Many thanks, both.
